#!/usr/bin/env pwsh
# chmod +x .git/hooks/*-commit
# https://sqlnotesfromtheunderground.wordpress.com/2018/01/01/git-pre-commit-hook-with-powershell/
# https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_redirection?view=powershell-7.1

$changes = git diff --name-only

$bq_t = @()
$bq_p = @()
#$air_cp = @()
#$air_dag = @()


foreach ($change in $changes) 
{

    $splitPath = $change.Split([char[]] "./")

    switch ($splitPath[0]) 
    {
        'Crush' 
        { 
            $prj = 'forfree-288615'
            switch ($splitPath[1]) 
            {
                'bq'  
                { switch ($splitPath[2]) 
                        {
                            't' {$bq_t += $change}
                            # "Get-Content $q.sql | bq query --project_id=$prj --use_legacy_sql=false"
                            'p' {$bq_p += $change}
                        }
                }

            }
        }
    }
}

# ALWAYS deploy Tables first
foreach ($t in $bq_t) 
{
    #$cmd = 
    Get-Content $t | bq query --project_id=$prj --use_legacy_sql=false --dry_run
    #Write-Output $cmd
}

foreach ($p in $bq_p) 
{    Get-Content $p | bq query --project_id=$prj --use_legacy_sql=false --dry_run   }

exit 0
# sq and sp do not contain('d-dat','-rnd','-dev','-uat')
